import { chmodSync, copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const PACKAGE = fileURLToPath(new URL("..", import.meta.url));
const LOCKFILE = join(PACKAGE, "..", "..", "pnpm-lock.yaml");
const IMPORTER = "packages/daemon";

/**
 * The exact versions pnpm installed for the daemon's own dependencies, read from
 * the `importers` section of the lockfile; workspace links are left out.
 */
export function lockedDependencies(
	lockfile: string = readFileSync(LOCKFILE, "utf8"),
): Record<string, string> {
	const versions: Record<string, string> = {};
	let section: "importer" | "dependencies" | undefined;
	let name: string | undefined;
	for (const line of lockfile.split("\n")) {
		if (/^ {2}\S/.test(line)) section = line.trim() === `${IMPORTER}:` ? "importer" : undefined;
		else if (section && /^ {4}\S/.test(line))
			section = line.trim() === "dependencies:" ? "dependencies" : "importer";
		else if (section === "dependencies" && /^ {6}\S/.test(line))
			name = line.trim().slice(0, -1).replace(/^'|'$/g, "");
		else if (section === "dependencies" && name && /^ {8}version: /.test(line)) {
			const version = line.trim().slice("version: ".length).split("(")[0] ?? "";
			if (!version.startsWith("link:")) versions[name] = version;
		}
	}
	if (Object.keys(versions).length === 0) throw new Error(`No ${IMPORTER} dependencies in the lockfile.`);
	return versions;
}

/** A `pi` command that runs the runtime's own Node on the engine, from wherever the runtime folder is. */
export function piWrapper(engineEntry: string): string {
	return `#!/bin/sh
# The engine's \`pi\` command for an installed Gentle Dot runtime (generated by build:runtime).
self=$0
while [ -L "$self" ]; do
	link=$(readlink "$self")
	case $link in
		/*) self=$link ;;
		*) self=$(dirname "$self")/$link ;;
	esac
done
runtime=$(CDPATH= cd -- "$(dirname -- "$self")/.." && pwd -P) || exit 1
exec "$runtime/node/bin/node" "$runtime/daemon/node_modules/${engineEntry}" "$@"
`;
}

/** The engine's `pi` entry inside `node_modules`, from its package's `bin` (its exports hide `package.json`). */
function engineEntry(): string {
	const engine = join("@earendil-works", "pi-coding-agent");
	const require = createRequire(join(PACKAGE, "package.json"));
	for (const dir of require.resolve.paths(engine) ?? []) {
		const manifest = join(dir, engine, "package.json");
		if (!existsSync(manifest)) continue;
		const bin = (JSON.parse(readFileSync(manifest, "utf8")) as { bin?: Record<string, string> }).bin?.pi;
		if (!bin) throw new Error("The engine package has no `pi` command.");
		return `@earendil-works/pi-coding-agent/${bin.replace(/^\.\//, "")}`;
	}
	throw new Error("The assistant engine is missing. Run `pnpm install`.");
}

/**
 * Builds the daemon part of the installed runtime into `outDir`: `daemon/cli.mjs`
 * (the daemon and the protocol bundled; the engine and `ws` external), the files it
 * finds next to itself, a `package.json` for a flat install of the external
 * dependencies, and `bin/pi`. Nothing is installed.
 */
export async function buildRuntime(outDir: string): Promise<void> {
	const daemon = join(outDir, "daemon");
	mkdirSync(join(daemon, "extensions"), { recursive: true });
	mkdirSync(join(outDir, "bin"), { recursive: true });
	const dependencies = lockedDependencies();
	await build({
		entryPoints: [join(PACKAGE, "src", "cli.ts")],
		outfile: join(daemon, "cli.mjs"),
		bundle: true,
		platform: "node",
		format: "esm",
		target: "node24",
		external: Object.keys(dependencies),
		logLevel: "error",
	});
	chmodSync(join(daemon, "cli.mjs"), 0o755);
	// The bundle finds these through `import.meta.url`, as the sources do in `src/`.
	copyFileSync(join(PACKAGE, "src", "identity.md"), join(daemon, "identity.md"));
	// The engine loads the guard with -e, and the guard imports its siblings.
	for (const name of ["command-code.ts", "approval-guard.ts", "screenshot-context.ts"]) {
		copyFileSync(join(PACKAGE, "src", "extensions", name), join(daemon, "extensions", name));
	}
	const manifest = { name: "gentle-dot-runtime", private: true, type: "module", dependencies };
	writeFileSync(join(daemon, "package.json"), `${JSON.stringify(manifest, null, "\t")}\n`);
	writeFileSync(join(outDir, "bin", "pi"), piWrapper(engineEntry()), { mode: 0o755 });
}
